# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Node-OPCUA
email: etienne.rossignon@sterfive.org
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
description: > # this means to ignore newlines until "baseurl:"
  Node-OPCUA, the OPCUA SDK for node.js.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://node-opcua.github.io" # the base hostname & protocol for your site
twitter_username: nodeopcua
github_username:  nodeopcua
github_user: node-opcua
github_repo_count:  20
github_skip_forks: true
# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
organisation: Sterfive
author: E. Rossignon
exclude:
  - vendor
  - theme
  -   .idea
