YUI.add("yuidoc-meta", function(Y) {
   Y.YUIDoc = { meta: {
    "classes": [
        "AcknowledgeMessage",
        "ActivateSessionRequest",
        "ActivateSessionResponse",
        "AddNodesItem",
        "AddNodesRequest",
        "AddNodesResponse",
        "AddNodesResult",
        "AddReferencesItem",
        "AddReferencesRequest",
        "AddReferencesResponse",
        "AddressSpace",
        "AggregateConfiguration",
        "AggregateFilter",
        "AnonymousIdentityToken",
        "ApplicationDescription",
        "ApplicationInstanceCertificate",
        "Argument",
        "AsymmetricAlgorithmSecurityHeader",
        "AttributeIds",
        "AttributeNameById",
        "AttributeOperand",
        "AxisInformation",
        "BaseEventType",
        "BaseNode\n\nBaseNode is the base class for all the OPCUA objects in the address space\nIt provides attributes and a set of references to other nodes.\nsee:\n{{#crossLink \"UAObject\"}}{{/crossLink}},\n{{#crossLink \"UAVariable\"}}{{/crossLink}},\n{{#crossLink \"Reference\"}}{{/crossLink}},\n{{#crossLink \"UAMethod\"}}{{/crossLink}},\n{{#crossLink \"UAView\"}}{{/crossLink}},\n{{#crossLink \"UAObjecType\"}}{{/crossLink}},\n{{#crossLink \"UADataType\"}}{{/crossLink}},\n{{#crossLink \"UAVariableType\"}}{{/crossLink}},",
        "BaseUAObject",
        "BinaryStream",
        "BinaryStreamSizeCalculator",
        "BrowseDescription",
        "BrowseDirection",
        "BrowseNextRequest",
        "BrowseNextResponse",
        "BrowsePath",
        "BrowsePathResult",
        "BrowsePathTarget",
        "BrowseRequest",
        "BrowseResponse",
        "BrowseResult",
        "BuildInfo",
        "CallMethodRequest",
        "CallMethodResult",
        "CallRequest",
        "CallResponse",
        "CancelRequest",
        "CancelResponse",
        "ChannelSecurityToken",
        "ChunkManager",
        "ClientMonitoredItem",
        "ClientMonitoredItemGroup",
        "ClientSecureChannelLayer",
        "ClientSession",
        "ClientSidePublishEngine\n\nThe ClientSidePublishEngine encapsulates the mechanism to\ndeal with a OPCUA Server and constantly sending PublishRequest\nThe ClientSidePublishEngine also performs  notification acknowledgements.\nFinally, ClientSidePublishEngine dispatch PublishResponse to the correct\nSubscription id callback",
        "ClientSubscription",
        "ClientTCP_transport",
        "CloseSecureChannelRequest",
        "CloseSecureChannelResponse",
        "CloseSessionRequest",
        "CloseSessionResponse",
        "ConditionInfo",
        "ConditionSnapshot",
        "ContentFilter",
        "ContentFilterElement",
        "ContentFilterElementResult",
        "ContentFilterResult",
        "CreateMonitoredItemsRequest",
        "CreateMonitoredItemsResponse",
        "CreateSessionRequest",
        "CreateSessionResponse",
        "CreateSubscriptionRequest",
        "CreateSubscriptionResponse",
        "DataChangeFilter",
        "DataChangeNotification",
        "DataValue",
        "DeleteMonitoredItemsRequest",
        "DeleteMonitoredItemsResponse",
        "DeleteNodesItem",
        "DeleteNodesRequest",
        "DeleteNodesResponse",
        "DeleteReferencesItem",
        "DeleteReferencesRequest",
        "DeleteReferencesResponse",
        "DeleteSubscriptionsRequest",
        "DeleteSubscriptionsResponse",
        "DiagnosticInfo",
        "EUInformation",
        "ElementOperand",
        "EndpointDescription",
        "Enum",
        "EnumValueType",
        "ErrorMessage",
        "EventData",
        "EventFieldList",
        "EventFilter",
        "EventFilterResult",
        "EventNotificationList",
        "ExpandedNodeId",
        "Factory",
        "FilterOperand",
        "FindServersOnNetworkRequest",
        "FindServersOnNetworkResponse",
        "FindServersRequest",
        "FindServersResponse",
        "GetEndpointsRequest",
        "GetEndpointsResponse",
        "HelloMessage",
        "HistoryData",
        "HistoryModifiedData",
        "HistoryReadDetails",
        "HistoryReadRequest",
        "HistoryReadResponse",
        "HistoryReadResult",
        "HistoryReadValueId",
        "HistoryServerCapabilities",
        "HistoryUpdateRequest",
        "HistoryUpdateResponse",
        "HistoryUpdateResult",
        "IssuedIdentityToken",
        "LiteralOperand",
        "LocalizedText",
        "MandatoryChildOrRequestedOptionalFilter\nreturn true if node is a mandatory child or a requested optional",
        "MdnsDiscoveryConfiguration",
        "MessageBuilder",
        "MessageBuilderBase",
        "MessageChunker",
        "ModelChangeStructure",
        "ModificationInfo",
        "ModifyMonitoredItemsRequest",
        "ModifyMonitoredItemsResponse",
        "ModifySubscriptionRequest",
        "ModifySubscriptionResponse",
        "MonitoredItem",
        "MonitoredItemCreateRequest",
        "MonitoredItemCreateResult",
        "MonitoredItemModifyRequest",
        "MonitoredItemModifyResult",
        "MonitoredItemNotification",
        "MonitoringFilter",
        "MonitoringParameters",
        "NodeCrawler",
        "NodeId",
        "NodeIdType",
        "NodeTypeDescription",
        "NotificationMessage",
        "OPCUABaseServer",
        "OPCUAClient",
        "OPCUAClientBase",
        "OPCUASecureObject",
        "OPCUAServer",
        "OPCUAServerEndPoint\n\nA sever end point is listening to one port",
        "OpenSecureChannelRequest",
        "OpenSecureChannelResponse",
        "OperationLimits",
        "PacketAssembler",
        "ParsingResult",
        "PublishRequest",
        "PublishResponse",
        "QualifiedName",
        "QueryDataDescription",
        "QueryDataSet",
        "QueryFirstRequest",
        "QueryFirstResponse",
        "QueryNextRequest",
        "QueryNextResponse",
        "Range",
        "ReadAtTimeDetails",
        "ReadEventDetails",
        "ReadProcessedDetails",
        "ReadRawModifiedDetails",
        "ReadRequest",
        "ReadResponse",
        "ReadValueId",
        "ReaderState",
        "RedundantServer",
        "Reference",
        "ReferenceDescription",
        "ReferenceType",
        "RegisterNodesRequest",
        "RegisterNodesResponse",
        "RegisterServer2Request",
        "RegisterServer2Response",
        "RegisterServerRequest",
        "RegisterServerResponse",
        "RegisteredServer",
        "RelativePath",
        "RelativePathElement",
        "RepublishRequest",
        "RepublishResponse",
        "RequestHeader",
        "ResponseHeader",
        "SamplingIntervalDiagnostics",
        "SecureMessageChunkManager",
        "SecurityPolicy",
        "SemanticChangeStructure",
        "SequenceHeader",
        "SequenceNumberGenerator",
        "ServerCapabilities",
        "ServerDiagnosticsSummary",
        "ServerEngine",
        "ServerOnNetwork",
        "ServerSecureChannelLayer",
        "ServerSession",
        "ServerSidePublishEngine\n a Publish Engine for a given session",
        "ServerStatus",
        "ServerTCP_transport",
        "ServiceCounter",
        "ServiceFault",
        "SessionContext",
        "SessionDiagnostics",
        "SessionSecurityDiagnostics",
        "SetMonitoringModeRequest",
        "SetMonitoringModeResponse",
        "SetPublishingModeRequest",
        "SetPublishingModeResponse",
        "SetTriggeringRequest",
        "SetTriggeringResponse",
        "SignatureData",
        "SignedSoftwareCertificate",
        "SimpleAttributeOperand",
        "Simulator",
        "StatusChangeNotification",
        "StatusCode",
        "Subscription",
        "SubscriptionAcknowledgement",
        "SubscriptionDiagnostics",
        "SymmetricAlgorithmSecurityHeader",
        "TCPErrorMessage",
        "TCP_transport",
        "TimeZone",
        "TimestampsToReturn",
        "ToolBrowsePath",
        "TransferResult",
        "TransferSubscriptionsRequest",
        "TransferSubscriptionsResponse",
        "TranslateBrowsePathsToNodeIdsRequest",
        "TranslateBrowsePathsToNodeIdsResponse",
        "TypeSchema",
        "UAAcknowledgeableConditionBase",
        "UAAlarmConditionBase",
        "UACertificateExpirationAlarm\n\nThis SystemOffNormalAlarmType is raised by the Server when the Server’s Certificate is within the ExpirationLimit\nof expiration. This alarm automatically returns to normal when the certificate is updated.",
        "UAConditionBase",
        "UADataType",
        "UADiscreteAlarm\n\nThe DiscreteAlarmType is used to classify Types into Alarm Conditions where the input for the\nAlarm may take on only a certain number of possible values (e.g. true/false,\nrunning/stopped/terminating).",
        "UAExclusiveDeviationAlarm",
        "UAExclusiveLevelAlarm",
        "UAExclusiveLimitAlarm",
        "UAExclusiveRateOfChangeAlarm",
        "UALimitAlarm",
        "UAMultiStateDiscreteType",
        "UANonExclusiveDeviationAlarm",
        "UANonExclusiveLimitAlarm",
        "UAObject",
        "UAObjectType",
        "UAOffNormalAlarm",
        "UAProxyManager",
        "UASystemOffNormalAlarm",
        "UATripAlarm\n\nThe TripAlarmType is a specialization of the OffNormalAlarmType intended to represent an equipment trip Condition.\nThe Alarm becomes active when the monitored piece of equipment experiences some abnormal fault such as a motor\nshutting down due to an overload Condition. This Type is mainly used for categorization.",
        "UATwoStateVariable",
        "UAVariable",
        "UAVariableType",
        "UnregisterNodesRequest",
        "UnregisterNodesResponse",
        "UserNameIdentityToken",
        "UserTokenPolicy",
        "Variant",
        "View",
        "ViewDescription",
        "WriteRequest",
        "WriteResponse",
        "WriteValue",
        "X509IdentityToken",
        "Xml2Json",
        "opcua"
    ],
    "modules": [
        "StatusCodes",
        "opcua.address_space",
        "opcua.address_space.AlarmsAndConditions",
        "opcua.address_space.types",
        "opcua.client",
        "opcua.data-value",
        "opcua.datamodel",
        "opcua.miscellaneous",
        "opcua.server",
        "opcua.server.simulation",
        "opcua.status-code",
        "opcua.transport",
        "opcua.utils",
        "opcua.variant",
        "service.filter.tools",
        "services.browse",
        "services.call",
        "services.discovery",
        "services.endpoints",
        "services.filter",
        "services.history",
        "services.node_management",
        "services.query",
        "services.read",
        "services.register-server",
        "services.register_node",
        "services.secure-channel",
        "services.session",
        "services.subscription",
        "services.translate-browse-path",
        "services.write",
        "xml2json\n\nnode -> see if https:__github.com_isaacs_sax-js could be used instead"
    ],
    "allModules": [
        {
            "displayName": "opcua.address_space",
            "name": "opcua.address_space"
        },
        {
            "displayName": "opcua.address_space.AlarmsAndConditions",
            "name": "opcua.address_space.AlarmsAndConditions"
        },
        {
            "displayName": "opcua.address_space.types",
            "name": "opcua.address_space.types"
        },
        {
            "displayName": "opcua.client",
            "name": "opcua.client"
        },
        {
            "displayName": "opcua.data-value",
            "name": "opcua.data-value"
        },
        {
            "displayName": "opcua.datamodel",
            "name": "opcua.datamodel"
        },
        {
            "displayName": "opcua.miscellaneous",
            "name": "opcua.miscellaneous"
        },
        {
            "displayName": "opcua.server",
            "name": "opcua.server"
        },
        {
            "displayName": "opcua.server.simulation",
            "name": "opcua.server.simulation"
        },
        {
            "displayName": "opcua.status-code",
            "name": "opcua.status-code"
        },
        {
            "displayName": "opcua.transport",
            "name": "opcua.transport"
        },
        {
            "displayName": "opcua.utils",
            "name": "opcua.utils"
        },
        {
            "displayName": "opcua.variant",
            "name": "opcua.variant"
        },
        {
            "displayName": "service.filter.tools",
            "name": "service.filter.tools"
        },
        {
            "displayName": "services.browse",
            "name": "services.browse"
        },
        {
            "displayName": "services.call",
            "name": "services.call",
            "description": "This Service is used to call (invoke) a list of Methods. Each method call is invoked within the context\n of an existing Session. If the Session is terminated, the results of the method’s execution cannot be\n returned to the Client and are discarded. This is independent of the task actually performed at the\n Server.\n This Service provides for passing input and output arguments to/from a method. These arguments\n are defined by Properties of the method."
        },
        {
            "displayName": "services.discovery",
            "name": "services.discovery"
        },
        {
            "displayName": "services.endpoints",
            "name": "services.endpoints"
        },
        {
            "displayName": "services.filter",
            "name": "services.filter"
        },
        {
            "displayName": "services.history",
            "name": "services.history"
        },
        {
            "displayName": "services.node_management",
            "name": "services.node_management"
        },
        {
            "displayName": "services.query",
            "name": "services.query"
        },
        {
            "displayName": "services.read",
            "name": "services.read"
        },
        {
            "displayName": "services.register-server",
            "name": "services.register-server"
        },
        {
            "displayName": "services.register_node",
            "name": "services.register_node"
        },
        {
            "displayName": "services.secure-channel",
            "name": "services.secure-channel"
        },
        {
            "displayName": "services.session",
            "name": "services.session"
        },
        {
            "displayName": "services.subscription",
            "name": "services.subscription"
        },
        {
            "displayName": "services.translate-browse-path",
            "name": "services.translate-browse-path"
        },
        {
            "displayName": "services.write",
            "name": "services.write"
        },
        {
            "displayName": "StatusCodes",
            "name": "StatusCodes"
        },
        {
            "displayName": "xml2json\n\nnode -> see if https://github.com/isaacs/sax-js could be used instead",
            "name": "xml2json\n\nnode -> see if https:__github.com_isaacs_sax-js could be used instead"
        }
    ],
    "elements": []
} };
});