YUI.add("yuidoc-meta", function(Y) {
   Y.YUIDoc = { meta: {
    "classes": [
        "AcknowledgeMessage",
        "ActivateSessionRequest",
        "ActivateSessionResponse",
        "AddNodesItem",
        "AddNodesRequest",
        "AddNodesResponse",
        "AddNodesResult",
        "AddReferencesItem",
        "AddReferencesRequest",
        "AddReferencesResponse",
        "AddressSpace",
        "AggregateConfiguration",
        "AnonymousIdentityToken",
        "ApplicationDescription",
        "ApplicationType",
        "Argument",
        "AsymmetricAlgorithmSecurityHeader",
        "AttributeIds",
        "AttributeOperand",
        "AxisInformation",
        "BaseNode",
        "BaseUAObject",
        "BinaryStream",
        "BinaryStreamSizeCalculator",
        "BrowseDescription",
        "BrowseNextRequest",
        "BrowseNextResponse",
        "BrowsePath",
        "BrowsePathResult",
        "BrowsePathTarget",
        "BrowseRequest",
        "BrowseResponse",
        "BrowseResult",
        "BuildInfo",
        "CallMethodRequest",
        "CallMethodResult",
        "CallRequest",
        "CallResponse",
        "CancelRequest",
        "CancelResponse",
        "ChannelSecurityToken",
        "ChunkManager",
        "ClientMonitoredItem",
        "ClientSecureChannelLayer",
        "ClientSession",
        "ClientSidePublishEngine",
        "ClientSubscription",
        "ClientTCP_transport",
        "CloseSecureChannelRequest",
        "CloseSecureChannelResponse",
        "CloseSessionRequest",
        "CloseSessionResponse",
        "ContentFilter",
        "ContentFilterElement",
        "ContentFilterElementResult",
        "ContentFilterResult",
        "CreateMonitoredItemsRequest",
        "CreateMonitoredItemsResponse",
        "CreateSessionRequest",
        "CreateSessionResponse",
        "CreateSubscriptionRequest",
        "CreateSubscriptionResponse",
        "DataChangeFilter",
        "DataChangeNotification",
        "DataValue",
        "DeleteMonitoredItemsRequest",
        "DeleteMonitoredItemsResponse",
        "DeleteNodesItem",
        "DeleteNodesRequest",
        "DeleteNodesResponse",
        "DeleteReferencesItem",
        "DeleteReferencesRequest",
        "DeleteReferencesResponse",
        "DeleteSubscriptionsRequest",
        "DeleteSubscriptionsResponse",
        "DiagnosticInfo",
        "EUInformation",
        "ElementOperand",
        "EncodeDecode",
        "EndpointDescription",
        "Enum",
        "EnumValueType",
        "ErrorMessage",
        "EventField",
        "EventFilter",
        "EventFilterResult",
        "EventNotificationList",
        "ExpandedNodeId",
        "Factory",
        "FilterOperand",
        "FilterOperator",
        "FindServersRequest",
        "FindServersResponse",
        "GetEndpointsRequest",
        "GetEndpointsResponse",
        "HelloMessage",
        "HistoryData",
        "HistoryModifiedData",
        "HistoryReadDetails",
        "HistoryReadRequest",
        "HistoryReadResponse",
        "HistoryReadResult",
        "HistoryReadValueId",
        "HistoryUpdateRequest",
        "HistoryUpdateResponse",
        "HistoryUpdateResult",
        "IssuedIdentityToken",
        "LiteralOperand",
        "LocalizedText",
        "MessageBuilder",
        "MessageBuilderBase",
        "MessageChunker",
        "MessageSecurityMode",
        "ModificationInfo",
        "ModifyMonitoredItemsRequest",
        "ModifyMonitoredItemsResponse",
        "ModifySubscriptionRequest",
        "ModifySubscriptionResponse",
        "MonitoredItem",
        "MonitoredItemCreateRequest",
        "MonitoredItemCreateResult",
        "MonitoredItemModifyRequest",
        "MonitoredItemModifyResult",
        "MonitoredItemNotification",
        "MonitoringFilter",
        "MonitoringParameters",
        "NodeCrawler",
        "NodeId",
        "NodeIdType",
        "NodeTypeDescription",
        "NotificationMessage",
        "OPCUABaseServer",
        "OPCUAClient",
        "OPCUAClientBase",
        "OPCUASecureObject",
        "OPCUAServer",
        "OPCUAServerEndPoint\n\nA sever end point is listening to one port",
        "OpenSecureChannelRequest",
        "OpenSecureChannelResponse",
        "PacketAssembler",
        "ParsingResult",
        "PublishRequest",
        "PublishResponse",
        "QualifiedName",
        "QueryDataDescription",
        "QueryDataSet",
        "QueryFirstRequest",
        "QueryFirstResponse",
        "QueryNextRequest",
        "QueryNextResponse",
        "Range",
        "ReadAtTimeDetails",
        "ReadEventDetails",
        "ReadProcessedDetails",
        "ReadRawModifiedDetails",
        "ReadRequest",
        "ReadResponse",
        "ReadValueId",
        "ReaderState",
        "Reference",
        "ReferenceDescription",
        "ReferenceType",
        "RegisterNodesRequest",
        "RegisterNodesResponse",
        "RegisterServerRequest",
        "RegisterServerResponse",
        "RegisteredServer",
        "RelativePath",
        "RelativePathElement",
        "RepublishRequest",
        "RepublishResponse",
        "RequestHeader",
        "ResponseHeader",
        "SecureMessageChunkManager",
        "SecurityPolicy",
        "SecurityTokenRequestType",
        "SequenceHeader",
        "SequenceNumberGenerator",
        "ServerDiagnosticsSummary",
        "ServerEngine",
        "ServerSecureChannelLayer",
        "ServerSession",
        "ServerSidePublishEngine",
        "ServerStatus",
        "ServerTCP_transport",
        "ServiceCounter",
        "ServiceFault",
        "SessionDiagnostics",
        "SetMonitoringModeRequest",
        "SetMonitoringModeResponse",
        "SetPublishingModeRequest",
        "SetPublishingModeResponse",
        "SetTriggeringRequest",
        "SetTriggeringResponse",
        "SignatureData",
        "SignedSoftwareCertificate",
        "SimpleAttributeOperand",
        "Simulator",
        "StatusChangeNotification",
        "StatusCode",
        "Subscription",
        "SubscriptionAcknowledgement",
        "SubscriptionDiagnostics",
        "SymmetricAlgorithmSecurityHeader",
        "TCPErrorMessage",
        "TCP_transport",
        "TimestampsToReturn",
        "ToolBrowsePath",
        "TransferResult",
        "TransferSubscriptionsRequest",
        "TransferSubscriptionsResponse",
        "TranslateBrowsePathsToNodeIdsRequest",
        "TranslateBrowsePathsToNodeIdsResponse",
        "TypeSchema",
        "UADataType",
        "UAObject",
        "UAObjectType",
        "UAVariable",
        "UAVariableType",
        "UnregisterNodesRequest",
        "UnregisterNodesResponse",
        "UserIdentityTokenType",
        "UserNameIdentityToken",
        "UserTokenPolicy",
        "Variant",
        "View",
        "ViewDescription",
        "WriteRequest",
        "WriteResponse",
        "WriteValue",
        "X509IdentityToken",
        "Xml2Json",
        "cryptoutils",
        "opcua"
    ],
    "modules": [
        "StatusCodes",
        "opcua.address_space",
        "opcua.address_space.types",
        "opcua.client",
        "opcua.datamodel",
        "opcua.helpers",
        "opcua.miscellaneous",
        "opcua.server",
        "opcua.server.simulation",
        "opcua.transport",
        "services.browse",
        "services.get_endpoints",
        "services.historizing",
        "services.method",
        "services.read",
        "services.register",
        "services.session",
        "services.subscription",
        "services.write",
        "xml2json"
    ],
    "allModules": [
        {
            "displayName": "opcua.address_space",
            "name": "opcua.address_space"
        },
        {
            "displayName": "opcua.address_space.types",
            "name": "opcua.address_space.types"
        },
        {
            "displayName": "opcua.client",
            "name": "opcua.client"
        },
        {
            "displayName": "opcua.datamodel",
            "name": "opcua.datamodel"
        },
        {
            "displayName": "opcua.helpers",
            "name": "opcua.helpers"
        },
        {
            "displayName": "opcua.miscellaneous",
            "name": "opcua.miscellaneous"
        },
        {
            "displayName": "opcua.server",
            "name": "opcua.server"
        },
        {
            "displayName": "opcua.server.simulation",
            "name": "opcua.server.simulation"
        },
        {
            "displayName": "opcua.transport",
            "name": "opcua.transport"
        },
        {
            "displayName": "services.browse",
            "name": "services.browse"
        },
        {
            "displayName": "services.get_endpoints",
            "name": "services.get_endpoints"
        },
        {
            "displayName": "services.historizing",
            "name": "services.historizing"
        },
        {
            "displayName": "services.method",
            "name": "services.method",
            "description": "This Service is used to call (invoke) a list of Methods. Each method call is invoked within the context\n of an existing Session. If the Session is terminated, the results of the method’s execution cannot be\n returned to the Client and are discarded. This is independent of the task actually performed at the\n Server.\n This Service provides for passing input and output arguments to/from a method. These arguments\n are defined by Properties of the method."
        },
        {
            "displayName": "services.read",
            "name": "services.read"
        },
        {
            "displayName": "services.register",
            "name": "services.register"
        },
        {
            "displayName": "services.session",
            "name": "services.session"
        },
        {
            "displayName": "services.subscription",
            "name": "services.subscription"
        },
        {
            "displayName": "services.write",
            "name": "services.write"
        },
        {
            "displayName": "StatusCodes",
            "name": "StatusCodes"
        },
        {
            "displayName": "xml2json",
            "name": "xml2json"
        }
    ],
    "elements": []
} };
});